import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Loader2, Mail, User, Phone, Building, MapPin } from 'lucide-react';
import { UserRole } from '@/contexts/AuthContext';
import { CreateUserData } from '@/hooks/useUserManagement';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { RoleDefinition } from '@/types/permissions';
import { validateEmail, validatePasswordStrength, validateFullName } from '@/utils/validation';

interface CreateUserModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreateUser: (userData: CreateUserData) => Promise<{ success: boolean; password?: string; error?: string }>;
  loading?: boolean;
}

export function CreateUserModal({
  open,
  onOpenChange,
  onCreateUser,
  loading = false,
}: CreateUserModalProps) {
  const { profile: currentUser } = useAuth();
  const [roles, setRoles] = useState<RoleDefinition[]>([]);
  const [rolesLoading, setRolesLoading] = useState(false);

  const [formData, setFormData] = useState<CreateUserData>({
    email: '',
    full_name: '',
    role: 'user',
    phone: '',
    department: '',
    position: '',
    password: '',
    company_id: undefined
  });
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});

  // Fetch roles from database when modal opens
  useEffect(() => {
    if (open && currentUser?.company_id) {
      fetchRoles();
    }
  }, [open, currentUser?.company_id]);

  const fetchRoles = async () => {
    if (!currentUser?.company_id) return;

    setRolesLoading(true);
    try {
      const { data, error } = await supabase
        .from('roles')
        .select('*')
        .eq('company_id', currentUser.company_id)
        .order('is_default', { ascending: false })
        .order('name', { ascending: true });

      if (error) throw error;

      setRoles(data || []);
    } catch (err) {
      console.error('Error fetching roles:', err);
      toast.error('Failed to load roles');
    } finally {
      setRolesLoading(false);
    }
  };

  const validateForm = () => {
    const errors: Record<string, string> = {};

    // Email validation
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!validateEmail(formData.email)) {
      errors.email = 'Please enter a valid email address';
    }

    // Full name validation
    if (!formData.full_name.trim()) {
      errors.full_name = 'Full name is required';
    }

    // Role validation
    if (!formData.role) {
      errors.role = 'Role is required';
    }

    // Password validation
    const passwordValidation = validatePasswordStrength(formData.password);
    if (!passwordValidation.valid) {
      errors.password = passwordValidation.error!;
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setSubmitting(true);
    try {
      const result = await onCreateUser(formData);
      if (result.success) {
        // If a password was generated by the backend and not provided by admin, show it to admin
        if (!formData.password && result.password) {
          // eslint-disable-next-line no-alert
          alert(`User created. Temporary password: ${result.password}`);
        }
        toast.success('User created');
        handleClose();
      } else {
        toast.error(result.error || 'Failed to create user');
        // surface validation errors if present
        if (result.error) setFormErrors(prev => ({ ...prev, general: result.error }));
      }
    } catch (err) {
      console.error('Create user error:', err);
      toast.error('Failed to create user');
    } finally {
      setSubmitting(false);
    }
  };

  const handleClose = () => {
    onOpenChange(false);
    setFormData({
      email: '',
      full_name: '',
      role: 'user',
      phone: '',
      department: '',
      position: '',
      password: '',
      company_id: undefined
    });
    setFormErrors({});
  };

  const handleInputChange = (field: keyof CreateUserData) => (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    setFormData(prev => ({ ...prev, [field]: e.target.value }));
    if (formErrors[field]) {
      setFormErrors(prev => ({ ...prev, [field]: '' }));
    }
  };

  const handleRoleChange = (role: UserRole) => {
    setFormData(prev => ({ ...prev, role }));
    if (formErrors.role) {
      setFormErrors(prev => ({ ...prev, role: '' }));
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Create New User</DialogTitle>
          <DialogDescription>
            Add a new user to your organization with specific role and permissions.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="full_name">Full Name *</Label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="full_name"
                  placeholder="John Doe"
                  value={formData.full_name}
                  onChange={handleInputChange('full_name')}
                  className={`pl-10 ${formErrors.full_name ? 'border-destructive' : ''}`}
                  disabled={loading}
                />
              </div>
              {formErrors.full_name && (
                <p className="text-sm text-destructive">{formErrors.full_name}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="email">Email *</Label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="email"
                  type="email"
                  placeholder="john@company.com"
                  value={formData.email}
                  onChange={handleInputChange('email')}
                  className={`pl-10 ${formErrors.email ? 'border-destructive' : ''}`}
                  disabled={loading}
                />
              </div>
              {formErrors.email && (
                <p className="text-sm text-destructive">{formErrors.email}</p>
              )}
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="role">Role *</Label>
            <Select value={formData.role} onValueChange={handleRoleChange} disabled={loading || rolesLoading || roles.length === 0}>
              <SelectTrigger className={formErrors.role ? 'border-destructive' : ''}>
                <SelectValue placeholder={rolesLoading ? 'Loading roles...' : 'Select a role'} />
              </SelectTrigger>
              <SelectContent>
                {rolesLoading ? (
                  <div className="px-2 py-2 text-sm text-muted-foreground">Loading roles...</div>
                ) : roles.length === 0 ? (
                  <div className="px-2 py-2 text-sm text-muted-foreground">No roles available</div>
                ) : (
                  roles.map((role) => (
                    <SelectItem key={role.id} value={role.name}>
                      <div className="flex flex-col">
                        <span className="font-medium">{role.name}</span>
                        {role.description && (
                          <span className="text-xs text-muted-foreground">{role.description}</span>
                        )}
                      </div>
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
            {formErrors.role && (
              <p className="text-sm text-destructive">{formErrors.role}</p>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="phone">Phone</Label>
              <div className="relative">
                <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="phone"
                  placeholder="+1 (555) 123-4567"
                  value={formData.phone}
                  onChange={handleInputChange('phone')}
                  className="pl-10"
                  disabled={loading}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="department">Department</Label>
              <div className="relative">
                <Building className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="department"
                  placeholder="Sales, IT, Finance..."
                  value={formData.department}
                  onChange={handleInputChange('department')}
                  className="pl-10"
                  disabled={loading}
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="position">Position</Label>
            <div className="relative">
              <MapPin className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="position"
                placeholder="Manager, Developer, Analyst..."
                value={formData.position}
                onChange={handleInputChange('position')}
                className="pl-10"
                disabled={loading}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="password">Password *</Label>
            <div className="relative">
              <Input
                id="password"
                type="password"
                placeholder="Set initial password (min 8 characters, uppercase, lowercase, numbers)"
                value={formData.password}
                onChange={handleInputChange('password')}
                className={`pl-3 ${formErrors.password ? 'border-destructive' : ''}`}
                disabled={loading}
              />
            </div>
            {formErrors.password && (
              <p className="text-sm text-destructive">{formErrors.password}</p>
            )}
            {!formErrors.password && formData.password && (
              <p className="text-xs text-success">✓ Password meets requirements</p>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={handleClose}
              disabled={loading || submitting}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={loading || submitting}>
              {loading || submitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create User'
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
